apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
        - name: greet
          image: leszko/greet
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: greet
spec:
  type: LoadBalancer
  selector:
    app: greet
  ports:
  - name: app
    port: 80
